name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Manila
          config_padding: 10
          config_order: base.header, base.repositories, languages, music

          base: header, repositories

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_music: yes
          plugin_music_provider: "spotify"
          plugin_music_token: "c82c9c57bb19403e84ebb1585fc64077, 8f3e9f3f6f2d4ebc8ea590ec59df0228, AQA3Jjw50hdTQjtLTXrBJ0qV0379eflRduSvg2bwEZWDTdqmka0vXKE57oJHLODGEFCwzNCEriHJfugndpwfhQU4Oam9--QbvIzZRasZItuF8c65mJOlqSq2Sdhhc23pDk0"
          plugin_music_mode: "recent"
